/* GENERATED by tools/object-layouts.mjs. DO NOT EDIT. */
#ifndef AOT_GENERATED_OBJECT_LAYOUTS_H
#define AOT_GENERATED_OBJECT_LAYOUTS_H
#include <stddef.h>
#include <stdint.h>
enum { AOT_SLOT_JS_VALUE = 1, AOT_SLOT_BOOLEAN = 2, AOT_SLOT_SPEC_LIST = 3 };
typedef struct { uint16_t id, slot_count, method_family_id; const uint16_t *slot_ids; const uint8_t *storage; } AotObjectLayoutDesc;

#define AOT_INTERNAL_SLOT_PRIVATE_ELEMENTS 1
#define AOT_INTERNAL_SLOT_PROTOTYPE 2
#define AOT_INTERNAL_SLOT_EXTENSIBLE 3
#define AOT_INTERNAL_SLOT_PARAMETER_MAP 4
#define AOT_INTERNAL_SLOT_STRING_DATA 5
#define AOT_INTERNAL_SLOT_DATA_VIEW 6
#define AOT_INTERNAL_SLOT_VIEWED_ARRAY_BUFFER 7
#define AOT_INTERNAL_SLOT_BYTE_LENGTH 8
#define AOT_INTERNAL_SLOT_BYTE_OFFSET 9
#define AOT_INTERNAL_SLOT_PROXY_HANDLER 10
#define AOT_INTERNAL_SLOT_PROXY_TARGET 11

#define AOT_METHOD_FAMILY_ORDINARY_OBJECT_METHODS 1
#define AOT_METHOD_FAMILY_ARRAY_EXOTIC_METHODS 2
#define AOT_METHOD_FAMILY_MAPPED_ARGUMENTS_EXOTIC_METHODS 3
#define AOT_METHOD_FAMILY_STRING_EXOTIC_METHODS 4
#define AOT_METHOD_FAMILY_PROXY_EXOTIC_METHODS 5
#define AOT_METHOD_FAMILY_COUNT 5

#define AOT_INTERNAL_METHOD_GET_PROTOTYPE_OF 1
#define AOT_INTERNAL_METHOD_SET_PROTOTYPE_OF 2
#define AOT_INTERNAL_METHOD_IS_EXTENSIBLE 3
#define AOT_INTERNAL_METHOD_PREVENT_EXTENSIONS 4
#define AOT_INTERNAL_METHOD_GET_OWN_PROPERTY 5
#define AOT_INTERNAL_METHOD_DEFINE_OWN_PROPERTY 6
#define AOT_INTERNAL_METHOD_HAS_PROPERTY 7
#define AOT_INTERNAL_METHOD_GET 8
#define AOT_INTERNAL_METHOD_SET 9
#define AOT_INTERNAL_METHOD_DELETE 10
#define AOT_INTERNAL_METHOD_OWN_PROPERTY_KEYS 11
#define AOT_INTERNAL_METHOD_COUNT 11
static const uint64_t aot_method_family_override_masks[] = {
  UINT64_C(0x0), /* OrdinaryObjectMethods */
  UINT64_C(0x20), /* ArrayExoticMethods */
  UINT64_C(0x3b0), /* MappedArgumentsExoticMethods */
  UINT64_C(0x430), /* StringExoticMethods */
  UINT64_C(0x7ff), /* ProxyExoticMethods */
};

static const uint16_t aot_layout_1_slots[] = { 2, 3, 1 };
static const uint8_t aot_layout_1_storage[] = { AOT_SLOT_JS_VALUE, AOT_SLOT_BOOLEAN, AOT_SLOT_SPEC_LIST };
static const uint16_t aot_layout_2_slots[] = { 2, 3, 4, 1 };
static const uint8_t aot_layout_2_storage[] = { AOT_SLOT_JS_VALUE, AOT_SLOT_BOOLEAN, AOT_SLOT_JS_VALUE, AOT_SLOT_SPEC_LIST };
static const uint16_t aot_layout_3_slots[] = { 2, 3, 5, 1 };
static const uint8_t aot_layout_3_storage[] = { AOT_SLOT_JS_VALUE, AOT_SLOT_BOOLEAN, AOT_SLOT_JS_VALUE, AOT_SLOT_SPEC_LIST };
static const uint16_t aot_layout_4_slots[] = { 2, 3, 6, 7, 8, 9, 1 };
static const uint8_t aot_layout_4_storage[] = { AOT_SLOT_JS_VALUE, AOT_SLOT_BOOLEAN, AOT_SLOT_BOOLEAN, AOT_SLOT_JS_VALUE, AOT_SLOT_JS_VALUE, AOT_SLOT_JS_VALUE, AOT_SLOT_SPEC_LIST };
static const uint16_t aot_layout_5_slots[] = { 10, 11, 1 };
static const uint8_t aot_layout_5_storage[] = { AOT_SLOT_JS_VALUE, AOT_SLOT_JS_VALUE, AOT_SLOT_SPEC_LIST };

static const AotObjectLayoutDesc aot_object_layouts[] = {
  { 1, 3, 1, aot_layout_1_slots, aot_layout_1_storage },
  { 2, 4, 1, aot_layout_2_slots, aot_layout_2_storage },
  { 3, 4, 1, aot_layout_3_slots, aot_layout_3_storage },
  { 4, 7, 1, aot_layout_4_slots, aot_layout_4_storage },
  { 5, 3, 1, aot_layout_5_slots, aot_layout_5_storage },
};
static const size_t aot_object_layout_count = 5;
#endif
