#!/bin/bash
# Run the whole opcode matrix and print a catalogue.
#
#   tools/js-sweep.sh [OUTDIR]
#
# THE POINT IS THAT NOTHING STOPS THE RUN. `out/js-sweep` prints one line per case and cannot
# report a case that ABORTS -- an abort is not catchable from inside the process, and a panic in
# the compiler is exactly the class of failure most worth cataloguing. So the sweeper announces
# each case on stderr before running it, and this driver restarts the sweeper after the case that
# killed it, records that case as CRASH, and carries on. A run with fifty distinct panics in it
# still finishes and still names all fifty.
#
# Output in OUTDIR (default out/sweep):
#   raw.txt        one line per case: "<index> <STATUS> <label> [:: detail]"
#   trace.txt      the sweeper's stderr, including the CASE announcements
#   catalogue.md   failures grouped by status and detail, with counts and an example each
set -u

here="$(cd "$(dirname "$0")/.." && pwd)"
out="${1:-$here/out/sweep}"
sweep="$here/out/js-sweep"

[ -x "$sweep" ] || { echo "build it first: coil build tools/js-sweep.coil -o out/js-sweep" >&2; exit 1; }
mkdir -p "$out"
raw="$out/raw.txt"; trace="$out/trace.txt"
: > "$raw"; : > "$trace"

total=$("$sweep" --total)
echo "sweeping $total cases" >&2

next=0
restarts=0
while [ "$next" -lt "$total" ]; do
  # A batch runs until it finishes or dies. `timeout` covers a case that hangs rather than aborts;
  # it is recovered the same way, because a hang also stops the result lines.
  timeout 900 "$sweep" --from "$next" --to "$total" >> "$raw" 2>> "$trace"
  rc=$?
  [ "$rc" -eq 0 ] && break

  # Which case died: the last one announced. Falling back to `next` covers a batch that died on
  # its very first case, before announcing anything.
  died=$(grep '^CASE ' "$trace" | tail -1 | awk '{print $2}')
  case "$died" in ''|*[!0-9]*) died=$next ;; esac
  [ "$died" -lt "$next" ] && died=$next

  label=$(grep "^CASE $died " "$trace" | tail -1 | cut -d' ' -f3-)

  # WHAT IT SAID ON THE WAY DOWN. "exit 134" is the same for a compiler that refused a construct by
  # name and a compiler that corrupted its own graph, and those are opposite outcomes -- one is the
  # design working, the other is a defect. The first stderr line after the announcement separates
  # them, so REFUSED and CRASH are different statuses in the catalogue and only CRASH is a finding.
  msg=$(awk -v want="CASE $died " 'index($0, want) == 1 { seen = 1; next }
                                    seen && /^CASE / { exit }
                                    seen && NF { print; exit }' "$trace")
  msg=${msg:-"(no message)"}
  if [ "$rc" -eq 124 ]; then
    echo "$died TIMEOUT ${label:-?} :: no result within the batch timeout" >> "$raw"
  elif [ "${msg#frontend: unsupported}" != "$msg" ]; then
    echo "$died REFUSED ${label:-?} :: $msg" >> "$raw"
  else
    echo "$died CRASH ${label:-?} :: $msg" >> "$raw"
  fi
  restarts=$((restarts + 1))
  next=$((died + 1))
done

echo "done; $restarts restart(s)" >&2

# ---------------------------------------------------------------------------
# The catalogue
# ---------------------------------------------------------------------------
# TWO CLASSES, AND THE SPLIT IS THE WHOLE VALUE OF THE REPORT.
#
# A probe that fails on its own also fails in roughly every pair it appears in, so a raw grouping
# buries ten real findings under ten thousand lines of the same ten. Splitting on "does this probe
# fail ALONE" turns that back into: a short list of broken constructs, and -- separately -- the
# pairs where both halves are fine and only the composition is not. The second list is the one
# worth reading first: every finding in docs/FUZZ-FINDINGS.md so far was of that kind.
python3 - "$out" <<'PYCAT'
import collections, os, re, sys

out = sys.argv[1]
raw = [l.rstrip("\n") for l in open(os.path.join(out, "raw.txt")) if l.strip()]

singles, pairs, order = {}, {}, []
for line in raw:
    parts = line.split(" ", 2)
    if len(parts) < 3:
        continue
    status = parts[1]
    label, _, detail = parts[2].partition(" :: ")
    label, detail = label.strip(), detail.strip()
    if "+" in label:
        pairs[tuple(label.split("+", 1))] = (status, detail)
    else:
        name = label.split("/")[0]
        prev = singles.get(name)
        if prev is None or (prev[0] == "OK" and status != "OK"):
            singles[name] = (status, detail)
            if name not in order:
                order.append(name)

broken = {n for n, (s, _) in singles.items() if s != "OK"}

def table(counter):
    yield "| status | detail | probes |"
    yield "|---|---|---|"
    for (st, d), names in sorted(counter.items(), key=lambda kv: (-len(kv[1]), kv[0])):
        yield "| `%s` | %s | %s |" % (st, (d or "-")[:120].replace("|", "\\|"), ", ".join(sorted(names)))

L = []
L.append("# JavaScript probe sweep")
L.append("")
L.append("Generated by `tools/js-sweep.sh`. %d cases: %d probes alone at three constants, then"
         % (len(raw), len(singles)))
L.append("every ordered pair. Probes are in `src/js_probes.coil`; one node process serves the whole")
L.append("run (`native/js-oracle/oracle.c`).")
L.append("")
L.append("Statuses: `OK` agree · `DIFF` both produced a number and they differ · `VERIFY` the graph")
L.append("is malformed · `EVAL` the evaluator stopped · `INDEX` the frontend would not index the")
L.append("source · `REFUSED` the frontend named a construct it does not support · `CRASH` it died")
L.append("without naming one · `TIMEOUT` no result in time.")
L.append("")
L.append("**`REFUSED` is not a finding.** It is the compiler declining a construct by name, which is")
L.append("the designed behaviour. `CRASH` is a finding: it died without saying why.")
L.append("")
L.append("## Totals")
L.append("")
L.append("| status | cases |")
L.append("|---|---|")
for st, n in collections.Counter(l.split(" ")[1] for l in raw if len(l.split(" ")) > 1).most_common():
    L.append("| `%s` | %d |" % (st, n))
L.append("")
L.append("## Broken on their own")
L.append("")
L.append("%d of %d probes fail alone. Each also fails in most of its ~%d pairings, which is why the"
         % (len(broken), len(singles), len(singles)))
L.append("case counts above are so much larger than the number of findings.")
L.append("")
g = collections.defaultdict(list)
for n, (st, d) in singles.items():
    if st != "OK":
        g[(st, d)].append(n)
L.extend(table(g))
L.append("")
L.append("## Composition only: both halves clean, the pair is not")
L.append("")
L.append("These are the interesting ones — nothing is wrong with either construct, so what failed is")
L.append("what the compiler carried across the join.")
L.append("")
comp = collections.defaultdict(list)
for (a, b), (st, d) in pairs.items():
    if st == "OK" or a in broken or b in broken:
        continue
    comp[(st, d)].append(a + "+" + b)
if not comp:
    L.append("None.")
else:
    L.append("| status | detail | pairs | cases |")
    L.append("|---|---|---|---|")
    for (st, d), names in sorted(comp.items(), key=lambda kv: -len(kv[1])):
        L.append("| `%s` | %s | %s | %d |"
                 % (st, (d or "-")[:100].replace("|", "\\|"), ", ".join("`%s`" % x for x in sorted(names)[:8]), len(names)))
L.append("")

open(os.path.join(out, "catalogue.md"), "w").write("\n".join(L) + "\n")
print("probes %d, broken alone %d, composition-only failures %d"
      % (len(singles), len(broken), sum(len(v) for v in comp.values())), file=sys.stderr)
PYCAT

echo "catalogue: $out/catalogue.md" >&2
awk '{print $2}' "$raw" | sort | uniq -c | sort -rn >&2
